name: Blog Entry Update

on:
  push:
    branches:
      - master

jobs:
  send_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to main repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: Ovis/blog.hitsujin.jp
          event-type: "update"
